# 当前文件和命令行中同配置冲突时，文件优先

async-dns=true
# 布尔值，不开启则使用操作系统提供的能力

async-dns-mode=multi
# 备选项cares dot doh multi

async-dns-server=dot://dot.360.cn,dot://dot.pub,https://dns.alidns.com/dns-query,tcp://180.184.1.1,udp://119.29.29.29
# multi支持多协议，加密协议优先

file-allocation=prealloc

# console-log-level=network

disable-ipv6=false

max-connection-per-server=64
split=24
# 两者最小值决定实际线程数
conf-precedence=conf

enable-http2=false
# 当前对H2连接复用和stream支持能力不强

enable-doh-http2=true

lowest-speed-limit=512K
min-split-size=1M
# 决定新开线程的最小条件

enable-http-pipelining=false
# 开启时每个range取固定大小
piece-length=1M
# 决定如何进行切片，实际Range大小取决于线程数

continue=true


uri-selector=adaptive

max-file-not-found=10
retry-wait=3
max-tries=10
# 决定的是HTTP错误的重试